### ISSUE TITLE
compile issues

### ISSUE THREAD

**Issue by netpipe** [PeachPy/EmCPython#1]
in opensuse 15.1 running the demo says site module missing ? 

node python.asm.js
ImportError: No module named site
Calling stub instead of sigaction()

**Comment by tecan** [comment]
oh i see i may have not made the tar correctly it seems empty 

./pack-modules.py -p emscripten -o pydata.tar   might be because of lib folder ?

**Comment by netpipe** [comment]
when i compile with libtar i get.   FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by netpipe** [comment]
was able to make it compile using codeblocks project file
![empython](https://i.imgur.com/wkgf8sD.png)
![compiler-setup](https://user-images.githubusercontent.com/172564/69022472-9e9c7280-0978-11ea-8aff-312da35ac8de.png)
`<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<CodeBlocks_project_file>
	<FileVersion major="1" minor="6" />
	<Project>
		<Option title="Python" />
		<Option pch_mode="0" />
		<Option compiler="emscripten" />
		<Build>
			<Target title="default">
				<Option output="./irrPy.html" prefix_auto="0" extension_auto="0" />
				<Option type="1" />
				<Option compiler="emscripten" />
				<Option projectResourceIncludeDirsRelation="1" />
			</Target>
			<Target title="emscripten">
				<Option output="./irrPy.html" prefix_auto="0" extension_auto="0" />
				<Option type="1" />
				<Option compiler="emscripten" />
				<Option projectLinkerOptionsRelation="1" />
				<Option projectIncludeDirsRelation="1" />
				<Option projectResourceIncludeDirsRelation="1" />
				<Option projectLibDirsRelation="1" />
				<Compiler>
					<Add directory="../../../Libs/Scripting/EmCPython/emscripten/include" />
					<Add directory="../../../Libs/irrlicht-ogl-es/irrlicht/include" />
					<Add directory="../../../Libs/Scripting/EmCPython/emscripten/include/python2.7" />
				</Compiler>
				<Linker>
					<Add option="-s TOTAL_MEMORY=64Mb" />
					<Add option="-s ASSERTIONS=2" />
					<Add option="--memory-init-file 0" />
					<Add option="--preload-file media/" />
					<Add option="-s EMULATE_FUNCTION_POINTER_CASTS=1" />
					<Add option="-s ERROR_ON_UNDEFINED_SYMBOLS=0" />
					<Add option="-s EXIT_RUNTIME=1" />
					<Add library="python2.7" />
					<Add library="tar" />
					<Add directory="../../../Libs/Scripting/EmCPython/emscripten/lib" />
					<Add directory="../../../Libs/irrlicht-ogl-es/irrlicht/lib/Linux" />
				</Linker>
			</Target>
		</Build>
		<VirtualTargets>
			<Add alias="All" targets="default;" />
		</VirtualTargets>
		<Compiler>
			<Add option="-D__EMSCRIPTEN__" />
			<Add option="-D_IRR_EMSCRIPTEN_PLATFORM_" />
			<Add option="-D_IRR_STATIC_LIB_" />
			<Add directory="../../../Libs/irrlicht-ogl-es/irrlicht/include" />
			<Add directory="../../../Libs/Scripting/EmCPython/Python-2.7/Include" />
			<Add directory="../../../Libs/Scripting/EmCPython/Python-2.7/" />
			<Add directory="../../../Libs/Scripting/EmCPython/emscripten/include" />
		</Compiler>
		<Linker>
			<Add library="python2.73" />
			<Add library="libtar" />
			<Add directory="../../../Libs/irrlicht-ogl-es/irrlicht/lib/Linux" />
			<Add directory="../../../Libs/Scripting/EmCPython/Python-2.7" />
			<Add directory="../../../Libs/Scripting/EmCPython/emscripten/lib" />
		</Linker>
		<Unit filename="main.c">
			<Option compilerVar="CC" />
		</Unit>
		<Extensions>
			<code_completion />
			<debugger />
		</Extensions>
	</Project>
</CodeBlocks_project_file>`

**Comment by netpipe** [comment]
i got the EmCPython compile working but when i add
-s EMULATE_FUNCTION_POINTER_CASTS=1 to irrlicht compile it says

FuncCastEmulation::NUM_PARAMS needs to be at least FuncCastEmulation::NUM_PARAMS needs to be at least 1717

is there a way around this without making a python plugin system ?

**Comment by netpipe** [comment]
new irrlicht  opengl-es fixed it.
